# Generated by Django 3.2.14 on 2022-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=80)),
                ('search_date', models.DateTimeField(verbose_name='search date')),
            ],
        ),
    ]
