# Generated by Django 3.2.14 on 2022-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(verbose_name='search date')),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
