# Generated by Django 3.2.14 on 2022-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20220731_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmeform',
            options={'verbose_name': 'Contact Form'},
        ),
        migrations.AlterField(
            model_name='contactmeform',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
