# Generated by Django 3.2.14 on 2022-07-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20220731_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMeForm',
            new_name='ContactMeModel',
        ),
    ]
