# Generated by Django 3.2.14 on 2022-09-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_contactmeform_contactmemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmemodel',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
