# Generated by Django 3.2.16 on 2023-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AlterField(
            model_name='contactmemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
