# Generated by Django 3.2.16 on 2023-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20230105_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post Form'},
        ),
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
    ]
