# Generated by Django 3.2.16 on 2023-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20230105_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Form',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='contactmemodel',
            options={'verbose_name': 'Contact ddd Form'},
        ),
    ]
