# Generated by Django 3.2.16 on 2023-01-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20230105_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
        migrations.AlterModelOptions(
            name='contactmemodel',
            options={'verbose_name': 'Contact Form'},
        ),
        migrations.RenameField(
            model_name='contactmemodel',
            old_name='date',
            new_name='created',
        ),
    ]
